pages:
  stage: deploy
  script:
    - mkdir public
    - cp index.html public/
    - cp *.svg public/ 2>/dev/null || true
    - cp *.png public/ 2>/dev/null || true
  artifacts:
    paths:
      - public
  only:
    - main
    - master 