pages:
  stage: deploy
  script:
    - mkdir public
    # Copy all HTML pages
    - cp index.html public/
    - cp getting-started.html public/
    # Copy any image assets
    - cp *.svg public/ 2>/dev/null || true
    - cp *.png public/ 2>/dev/null || true
    - cp *.jpg public/ 2>/dev/null || true
    - cp *.jpeg public/ 2>/dev/null || true
    - cp *.ico public/ 2>/dev/null || true
    # Copy any CSS/JS assets if they exist
    - cp *.css public/ 2>/dev/null || true
    - cp *.js public/ 2>/dev/null || true
    # List what we're deploying (for debugging)
    - ls -la public/
  artifacts:
    paths:
      - public
  only:
    - main
    - master 