stages:
  - Deploy
  - Publish

pages:
  stage: Deploy
  script:
    - mkdir -p public
    - cp index.html public/
    - cp getting-started.html public/ || true
    - cp *.svg public/ 2>/dev/null || true
    - cp *.png public/ 2>/dev/null || true
    - cp *.jpg public/ 2>/dev/null || true
    - cp *.jpeg public/ 2>/dev/null || true
    - cp *.ico public/ 2>/dev/null || true
    - cp *.css public/ 2>/dev/null || true
    - cp *.js public/ 2>/dev/null || true
    - ls -la public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

github_publish:
  stage: Publish
  image: alpine/git
  variables:
    GIT_STRATEGY: fetch
    GIT_DEPTH: "0"
  script:
    - mkdir -p ~/.ssh
    - echo "$GITHUB_DEPLOY_KEY" | sed -e 's/\r$//' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - git push git@github.com:${GITHUB_REPO}.git HEAD:refs/heads/${CI_COMMIT_REF_NAME} --force
    - git push git@github.com:${GITHUB_REPO}.git --tags
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'